services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring
    extra_hosts:
      - "host.local:host-gateway"
    ports:
      - "${PROMETHEUS_PORT:-9090}:${PROMETHEUS_PORT:-9090}"
    volumes:
      - ./tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./backup/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:${PROMETHEUS_PORT:-9090}'

  dcgm:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:4.3.1-4.4.0-ubuntu22.04
    container_name: dcgm
    networks:
      - monitoring
    extra_hosts:
      - "host.local:host-gateway"
    volumes:
      - ./tools/dcgm-exporter:/etc/dcgm-exporter
    environment:
      - DCGM_EXPORTER_LISTEN=:${DCGM_EXPORTER_PORT:-9400}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    cap_add:
      - SYS_ADMIN

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "${GRAFANA_PORT:-9999}:3000"
    volumes:
      - ./tools/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./tools/grafana/traditional-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./backup/grafana_provisioning/provisioning:/etc/grafana/provisioning
      - ./backup/grafana_provisioning/dashboards:/var/lib/grafana/dashboards
      - ./backup/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - quickwit
      - jaeger

networks:
  monitoring:
    driver: bridge
