global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: dcgm
    static_configs:
      - targets: ["localhost:9400"]
